spring:
  application:
    name: gateway-demo
  cloud:
    gateway:
      routes:
        - id: member
          uri: lb://server-member/
          filters:
            - StripPrefix=1
          predicates:
            - Path=/member/**
      discovery:
        locator:
          enabled: true
    nacos:
      discovery:
        server-addr: 127.0.0.1:8847
server:
  port: 83